# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - RentakWebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2785ECACA1F74474857DB7BC75D20244 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C395EECE54E8461F8154C9141044312D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC2145A6A7854C04BA0CDE29CAD022E9 }}

      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.json') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
            ${{ runner.os }}-nextjs-

      - name: bun install, build, and test
        run: |
          bun install
          bun run build
          bun run test --if-present

      # - name: Zip artifact for deployment
      # run: zip release.zip ./* -r

      - name: Add .next folder to zip artifact for deployment
        run: cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/ && cp -r .next/server .next/standalone/.next/ && zip release.zip ./.next/standalone -r

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RentakWebsite"
          slot-name: "production"
          package: release.zip
          clean: true
